export const listaZakupow = [
    'agrest',
    'ananas',
    'banany',
    'batonik czekoladowy',
    'boczek',
    'bombonierka',
    'borówki',
    'bób',
    'brokuły',
    'brzoskwinie',
    'budyń czekoladowy',
    'budyń waniliowy',
    'bułki',
    'buraki',
    'cebula',
    'chleb biały',
    'chleb razowy',
    'chleb tostowy',
    'chrzan',
    'chusteczki do nosa',
    'ciastka kruche',
    'cukier biały',
    'cukier brązowy',
    'czekolada biała',
    'czekolada gorzka',
    'czekolada mleczna',
    'czereśnie',
    'długopis',
    'dorsz',
    'durszlak',
    'dynia',
    'dżem morelowy',
    'dżem truskawkowy',
    'dżem wiśniowy',
    'fasola',
    'galaretka agrestowa',
    'galaretka brzoskwiniowa',
    'galaretka malinowa',
    'galaretka truskawkowa',
    'galaretka wiśniowa',
    'garnek',
    'grabie',
    'groszek zielony',
    'gruszki',
    'grzebień',
    'guma do żucia',
    'gumka',
    'guziki',
    'gwoździe',
    'herbata czarna',
    'herbata zielona',
    'igły',
    'indyk',
    'jabłka',
    'jagody',
    'jajka',
    'jogurt naturalny',
    'jogurt owocowy',
    'kabanosy',
    'kaczka',
    'kakao',
    'kalafior',
    'kalarepa',
    'kapusta',
    'karp',
    'kasza gryczana',
    'kasza jaglana',
    'kasza jęczmienna',
    'kasza manna',
    'kawa',
    'keczup',
    'kefir',
    'kiełbasa',
    'kisiel brzoskwiniowy',
    'kisiel malinowy',
    'kisiel truskawkowy',
    'kisiel wiśniowy',
    'kminek',
    'kubek',
    'kukurydza',
    'kurczak',
    'landrynki',
    'linijka',
    'liść laurowy',
    'lizaki',
    'lody orzechowe',
    'lody owocowe',
    'lody śmietankowe',
    'lody waniliowe',
    'łosoś',
    'majeranek',
    'majonez',
    'makaron',
    'makrela',
    'maliny',
    'mandarynki',
    'marchewka',
    'margaryna',
    'masło',
    'masło orzechowe',
    'maślanka',
    'mąka',
    'mięso mielone',
    'migdały',
    'miód',
    'miska',
    'mleko 1,5%',
    'mleko 2%',
    'mleko 3,5%',
    'mleko w proszku',
    'młotek',
    'morele',
    'musztarda',
    'mydło',
    'nici',
    'notes',
    'nożyczki',
    'nóż',
    'obcęgi',
    'ocet',
    'ogórki',
    'olej',
    'oliwa',
    'oliwki',
    'ołówek',
    'oregano',
    'orzechy',
    'oscypek',
    'papier toaletowy',
    'papryka',
    'parówki',
    'pasta do butów',
    'pasta do zębów',
    'patelnia',
    'pączki',
    'pestki dyni',
    'pestki słonecznika',
    'pieczarki',
    'pieprz',
    'pierogi',
    'pietruszka',
    'pilniczek',
    'piwo',
    'płatki kukurydziane',
    'płatki owsiane',
    'płyn do mycia naczyń',
    'płyn do płukania',
    'pomarańcze',
    'pomidory',
    'por',
    'powidła śliwkowe',
    'proszek do pieczenia',
    'proszek do prania',
    'ręcznik',
    'rodzynki',
    'ryż',
    'rzodkiewka',
    'salaterka',
    'sałata',
    'seler',
    'ser pleśniowy',
    'ser żółty',
    'serek homogenizowany',
    'skarpetki',
    'smalec',
    'sok jabłkowy',
    'sok pomarańczowy',
    'sok pomidorowy',
    'sól',
    'spinki do włosów',
    'szampon',
    'szczoteczka do zębów',
    'szczotka do włosów',
    'szczypior',
    'szklanki',
    'szpinak',
    'śledź',
    'śliwki',
    'śmietana 12%',
    'śmietana 18%',
    'śmietana 30%',
    'śmietana 36%',
    'śrubokręt',
    'talerze',
    'taśma klejąca',
    'truskawki',
    'twaróg chudy',
    'twaróg półtłusty',
    'twaróg tłusty',
    'wafelki',
    'wafle',
    'wątróbka',
    'wędlina',
    'widelec',
    'wino białe',
    'wiórki kokosowe',
    'wiśnie',
    'włoszczyzna',
    'woda',
    'zeszyt',
    'ziemniaki',
    'żelatyna',
    'żelki',
];
